/**
 * Compacts a chat message by removing unnecessary words and punctuation
 * while preserving the core meaning and information
 * @param {string} message - The original message to compact
 * @returns {string} - The compacted message
 */
export default function compactMessage(message) {
  if (!message || typeof message !== "string") {
    return "";
  }

  // Basic cleanup - remove punctuation but keep ? and !
  const cleaned = message
    .trim()
    .toLowerCase()
    .replace(/[^\w\s?!]/g, " ")
    .replace(/\s+/g, " ");

  // Tokenize into words
  const words = cleaned.split(" ").filter((word) => word.length > 0);

  // Stop words to remove (common unnecessary words)
  const stopWords = new Set([
    "a",
    "an",
    "and",
    "the",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "must",
    "can",
    "shall",
    "this",
    "that",
    "these",
    "those",
    "i",
    "you",
    "he",
    "she",
    "it",
    "we",
    "they",
    "me",
    "him",
    "her",
    "us",
    "them",
    "my",
    "your",
    "his",
    "her",
    "its",
    "our",
    "their",
    "in",
    "on",
    "at",
    "by",
    "for",
    "with",
    "from",
    "to",
    "of",
    "about",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "up",
    "down",
    "out",
    "off",
    "over",
    "under",
    "again",
    "further",
    "then",
    "once",
    "very",
    "too",
    "really",
    "quite",
    "rather",
    "much",
    "many",
    "more",
    "most",
    "some",
    "any",
    "all",
    "just",
    "only",
    "also",
    "even",
    "still",
    "like",
    "get",
    "got",
    "go",
    "going",
    "goes",
    "went",
    "come",
    "came",
    "coming",
    "take",
    "took",
    "taking",
    "make",
    "made",
    "making",
    "say",
    "said",
    "saying",
    "see",
    "saw",
    "seen",
    "know",
    "knew",
    "known",
    "think",
    "thought",
    "thinking",
    "want",
    "wanted",
    "wanting",
    "use",
    "used",
    "using",
    "now",
    "here",
    "there",
    "where",
    "way",
    "well",
    "back",
    "little",
    "good",
    "great",
    "right",
    "old",
    "new",
    "first",
    "last",
    "long",
    "own",
    "other",
    "each",
    "which",
    "their",
    "than",
    "them",
    "been",
    "who",
    "oil",
    "sit",
    "but",
    "not",
    "what",
    "all",
    "were",
    "they",
    "we",
    "when",
    "your",
    "said",
    "each",
    "she",
    "which",
    "do",
    "how",
    "if",
    "will",
    "up",
    "other",
    "about",
    "out",
    "many",
    "then",
    "them",
    "so",
    "some",
    "her",
    "would",
    "there",
    "into",
    "him",
    "time",
    "two",
    "more",
    "these",
    "go",
    "no",
    "way",
    "could",
    "my",
    "than",
    "first",
    "been",
    "call",
    "who",
    "its",
    "now",
    "find",
    "long",
    "down",
    "day",
    "did",
    "get",
    "come",
    "made",
    "may",
    "part",
  ]);

  // Important words to always keep (tech/chat related)
  const keepWords = new Set([
    "help",
    "error",
    "problem",
    "fix",
    "bug",
    "issue",
    "code",
    "function",
    "how",
    "why",
    "need",
    "work",
    "working",
    "yes",
    "ok",
    "okay",
    "please",
    "thanks",
    "thank",
    "sorry",
    "hello",
    "hi",
    "bye",
    "javascript",
    "react",
    "css",
    "html",
    "api",
    "data",
    "file",
    "app",
    "website",
    "page",
    "button",
    "click",
    "user",
    "login",
    "password",
    "email",
    "database",
    "server",
    "client",
    "browser",
    "npm",
    "install",
    "package",
    "library",
    "framework",
    "component",
  ]);

  // Filter words based on rules
  const compactedWords = words.filter((word) => {
    // Always keep numbers
    if (/^\d+$/.test(word)) return true;

    // Always keep words in keepWords list
    if (keepWords.has(word)) return true;

    // Keep question/exclamation markers
    if (word.includes("?") || word.includes("!")) return true;

    // Skip stop words
    if (stopWords.has(word)) return false;

    // Keep meaningful words (length > 2)
    if (word.length > 2) return true;

    // Keep some important short words
    if (["no", "ok", "hi", "js", "ai", "ui", "db"].includes(word)) return true;

    return false;
  });

  return compactedWords.join(" ");
}
