name: Playwright Tests

on:
  push:
    branches: [main, dev2]
  pull_request:
    branches: [main, dev2]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --immutable --immutable-cache
    
    - name: Get installed Playwright version
      id: playwright-version
      run: echo "version=$(yarn playwright --version | cut -d' ' -f2)" >> $GITHUB_OUTPUT
    
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
    
    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: yarn playwright install --with-deps
    
    - name: Run Playwright tests
      run: yarn playwright test
    
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30